apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-pool"
spec:
  cidrs:
    - cidr: "192.168.2.64/28"

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium-bgp-policy
spec:
  nodeSelector:
    matchLabels:
      peering: "yes"
  virtualRouters:
    - localASN: 65001
      neighbors:
        - peerASN: 65000
          peerAddress: 10.168.2.1/32
      serviceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx



# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: "cilium-pool"
# spec:
#   cidrs:
#     - cidr: "192.168.2.48/29"  # covers .48-.55
#     - cidr: "192.168.2.56/30"  # covers .56-.59
#     - cidr: "192.168.2.60/31"  # covers .60-.61
#     - cidr: "192.168.2.62/32"  # covers .62 only
#     - cidr: "192.168.2.63/32"  # covers .63 only
#     - cidr: "192.168.2.64/28"  # covers .64-.79
#     - cidr: "192.168.2.64/27"  # covers .64-.95

