apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
  namespace: spark-operator
spec:
  serviceAccountName: spark-operator
  containers:
    - name: internal-kubectl
      image: bitnami/kubectl
      command:
      - sleep 
      - "infinity"      