apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-data
  namespace: prometheus
  labels:
    type: nfs
    app: MYAPP
spec:
  storageClassName: k8s-nfs-class
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi