NUM_WORKER_NODES=3
IP_NW="192.168.2."
IP_START=130

Vagrant.configure("2") do |config|
  config.vm.provision "shell", env: {"IP_NW" => IP_NW, "IP_START" => IP_START}, inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START)) master-node" >> /etc/hosts
      echo "$IP_NW$((IP_START+1)) worker-node01" >> /etc/hosts
      echo "$IP_NW$((IP_START+2)) worker-node02" >> /etc/hosts
      echo "$IP_NW$((IP_START+3)) worker-node03" >> /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = true
  config.vm.boot_timeout = 1200

  config.vm.define "master" do |master|
    # master.vm.box = "bento/ubuntu-18.04"
    master.vm.hostname = "master-node"
    master.vm.network "public_network", bridge: "QLogic BCM5709C Gigabit Ethernet (NDIS VBD Client) #2", ip: IP_NW + "#{IP_START}"
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 6144
        vb.cpus = 4
    end
    master.vm.provision "shell", path: "scripts/common.sh"
    master.vm.provision "shell", path: "scripts/master.sh"
    if Vagrant.has_plugin?("vagrant-timezone")
       config.timezone.value = :host
    end
  end

  (1..NUM_WORKER_NODES).each do |i|

  config.vm.define "node0#{i}" do |node|
    node.vm.hostname = "worker-node0#{i}"
    node.vm.network "public_network", bridge: "QLogic BCM5709C Gigabit Ethernet (NDIS VBD Client) #2", ip: IP_NW + "#{IP_START + i}"
    node.vm.provider "virtualbox" do |vb|
        vb.memory = 6144
        vb.cpus = 4
    end
    node.vm.provision "shell", path: "scripts/common.sh"
    node.vm.provision "shell", path: "scripts/node.sh"
    if Vagrant.has_plugin?("vagrant-timezone")
       config.timezone.value = :host
    end
  end

  end
end 