apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
spec:
  selector:
    matchLabels:
      app: apple
  replicas: 1
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
      - name: apple
        image: hashicorp/http-echo
        args:
        - "-text=apple"
        ports:
        - containerPort: 5678

---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
  # annotations:
  #   "io.cilium/lb-ipam-ips": "192.168.2.75"
spec:
  selector:
    app: apple
  ports:
    - port: 5678
      targetPort: 5678
  type: ClusterIP

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple-ingress
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
        - path: /apple
          pathType: Prefix
          backend:
            service:
              name: apple-service
              port:
                number: 5678




# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: apple-network-policy
# spec:
#   podSelector:
#     matchLabels: {}
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels: {} # This allows ingress from all pods
#   egress:
#   - to:
#     - podSelector:
#         matchLabels: {} # This allows egress to all pods

