apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8sgrafana.rupesh.com
  namespace: grafana
spec:
  secretName: k8sgrafana.rupesh.com-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "k8sgrafana.rupesh.com"
  dnsNames:
    - "k8sgrafana.rupesh.com"
  issuerRef:
    name: p90s-ca-issuer
    kind: ClusterIssuer
