apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../fruits

patches:
  - path: apple-deployment-patch.yaml
    target:
      kind: Deployment
      path: spec/template/spec/containers
      o: replace
  - path: apple-ingress-patch.yaml
    target:
      kind: Ingress
  - path: apple-service-patch.yaml
    target:
      kind: Service

namePrefix: apple-