NUM_WORKER_NODES=2
IP_NW="192.168.2."
IP_START=104

Vagrant.configure("2") do |config|
  config.vm.provision "shell", env: {"IP_NW" => IP_NW, "IP_START" => IP_START}, inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START)) ether-node0" >> /etc/hosts
      echo "$IP_NW$((IP_START+1)) ether-node01" >> /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-21.10"
  config.vm.box_check_update = true
  config.vm.boot_timeout = 1200

  (1..NUM_WORKER_NODES).each do |i|

    config.vm.define "ether0#{i}" do |ether|
      # master.vm.box = "bento/ubuntu-18.04"
      ether.vm.hostname = "ether-node0#{i}"
      ether.vm.network "public_network", bridge: "QLogic BCM5709C Gigabit Ethernet (NDIS VBD Client) #2", ip: IP_NW + "#{IP_START + i}"
      ether.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 4
      end
      ether.vm.provision "shell", path: "scripts/ether.sh"
      if Vagrant.has_plugin?("vagrant-timezone")
         config.timezone.value = :host
      end
    end

  end

end

#  sudo su -
#  vagrant/vagrant