apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8s-local-storage
  local:
    path: /mnt/disk/pvs-vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node01