apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zones
  namespace: core-dns
data:
  db.rupesh.org: |
    $TTL  30M
    @   IN  SOA  ns1.rupesh.org.  rupesh.org.  (
                    2019041900  ; Serial
                    4H          ; Refresh
                    1H          ; Retry
                    7D          ; Expire
                    4H )        ; Negative Cache TTL
        IN  NS  ns1

    ns1                       IN  A   192.168.1.8
    apple.rupesh.org.         IN  A   192.168.1.3


