NUM_WORKER_NODES=1
IP_NW="10.0.0."
IP_START=138

Vagrant.configure("2") do |config|
  config.vm.provision "shell", env: {"IP_NW" => IP_NW, "IP_START" => IP_START}, inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START)) keycloak.rupesh.com" >> /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = true
  config.vm.boot_timeout = 1200

  # Define the synced folder here
  # config.vm.synced_folder "/media/rupesh/Data/UT/", "/base-think/"

  (1..NUM_WORKER_NODES).each do |i|

    config.vm.define "keycloak" do |base|
      # master.vm.box = "bento/ubuntu-18.04"
      base.vm.hostname = "keycloak.rupesh.com"
      base.vm.network "public_network", bridge: "eno1", ip: IP_NW + "#{IP_START + i}"
      base.vm.provider "virtualbox" do |vb|
          vb.memory = 4096
          vb.cpus = 6
      end
      base.vm.provision "shell", path: "scripts/install.sh"
      base.vm.provision "shell", path: "scripts/add.sh"
      base.vm.provision "shell", path: "scripts/keycloak.sh"
      if Vagrant.has_plugin?("vagrant-timezone")
         config.timezone.value = :host
      end
    end

  end

end

#  sudo su -
#  vagrant/vagrant
