apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio

---

apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: "minio"
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio