{
 "title": "K8S Control Plane",
 "description": "Metrics for API Server, Controller and Scheduler.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API Server Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server RPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Current Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests) by (requestKind)",
     "legendFormat": "{{requestKind}}"
    }
   ]
  },
  {
   "title": "Latency - p99 (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_slo_duration_seconds_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le) ) / 1e+06"
    }
   ]
  },
  {
   "title": "API Server Response Duration (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT\"}[5m])) ",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "API Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Server Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Server Requests (by Verb)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "count by(verb) (apiserver_request_total)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Requests (by Resource)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Requests by client (non-kube-*)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{client!~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (client)>0",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "API Requests by client (kube-*)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{client=~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (client)>0",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "API Server Requests by server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(rate(apiserver_request_total[5m])) by (instance)>0",
     "legendFormat": "{{instance}} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le, resource) ) / 1e+06",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Response Duration - CONNECT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb=~\"CONNECT\"}[5m])) by (resource)/sum(rate(apiserver_request_duration_seconds_count{verb=~\"CONNECT\"}[5m])) by (resource)>0",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Kube Controller Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Has Leader?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(leader_election_master_status{component=\"kube-controller-manager\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(volumes_depth)\r", "legendFormat": "volumes" },
    { "expr": "sum(deployment_depth)\r", "legendFormat": "deployment" },
    { "expr": "sum(replicaset_depth)\r", "legendFormat": "replicaset_depth" },
    { "expr": "sum(service_depth)\r", "legendFormat": "service_depth" },
    { "expr": "sum(serviceaccount_depth)\r", "legendFormat": "serviceaccount_depth" },
    { "expr": "sum(endpoint_depth)\r", "legendFormat": "endpoint_depth" },
    { "expr": "sum(daemonset_depth)\r", "legendFormat": "daemonset_depth" },
    { "expr": "sum(statefulset_depth)\r", "legendFormat": "statefulset_depth" },
    {
     "expr": "sum(replicationmanager_depth)\r",
     "legendFormat": "replicationmanager_depth"
    },
    {
     "expr": "sum(horizontalpodautoscaler_depth)",
     "legendFormat": "horizontalpodautoscaler_depth"
    }
   ]
  },
  {
   "title": "Controller Manager Adds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(volumes_adds[5m])\r", "legendFormat": "volumes" },
    { "expr": "rate(deployment_adds[5m])\r", "legendFormat": "deployment" },
    { "expr": "rate(replicaset_adds[5m])\r", "legendFormat": "replicaset" },
    { "expr": "rate(service_adds[5m])\r", "legendFormat": "service" },
    { "expr": "rate(endpoint_adds[5m])\r", "legendFormat": "endpoints" },
    { "expr": "rate(daemonset_adds[5m])\r", "legendFormat": "daemonsets" },
    { "expr": "rate(statefulset_adds[5m])\r", "legendFormat": "statefulsets" },
    {
     "expr": "rate(horizontalpodautoscaler_adds[5m])",
     "legendFormat": "horizontalpodautoscaler"
    }
   ]
  },
  {
   "title": "Kube Scheduler Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Has Leader?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(leader_election_master_status{component=\"kube-scheduler\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scheduler Attempts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(scheduler_schedule_attempts_total[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Scheduler Duration ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_e2e_scheduling_duration_seconds_sum[5m]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}