apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: config
data:
  config: |
    peers:
    - peer-address: 6.5.3.1
      peer-asn: 65310
      my-asn: 65201
      router-id: 6.4.5.20
      source-address: 6.4.5.20
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [worker-node01]
    - peer-address: 6.5.3.2
      peer-asn: 65320
      my-asn: 65201
      router-id: 6.4.5.21
      source-address: 6.4.5.21
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [worker-node02]
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.10.0/24