apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: core-dns
data:
  Corefile: |
    .:53 {
        # Enable logging to STDOUT
        log
        # Print errors to STDOUT
        errors
        # Automatically load changes to the Corefile
        reload 30s
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        rewrite name apple.rtr.com apple-service.playground.svc.cluster.local
        forward . /etc/resolv.conf
        # Return HTTP 200 OK on :8080 when CoreDNS is running
        health
        # Return HTTP 200 OK on :8081 when CoreDNS and plugins are ready
        ready
    }        
    rtr.com:53 {
        errors
        cache 30
        forward . 192.168.1.3
        log
    }


