apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: core-dns
data:
  Corefile: |
    .:53 {
        # Automatically load zone files mounted in the "zones" directory
        auto {
            directory /etc/coredns/zones
        }
        # Enable logging to STDOUT
        log
        # rewrite name rtr.rupesh.com apple.rupesh.org
        hosts {
          192.168.1.3 rtr.rupesh.com
          fallthrough
        }
        forward . 192.168.1.8 /etc/resolv.conf        
        # Print errors to STDOUT
        errors
        # Automatically load changes to the Corefile
        reload 30s
        # Round-robin A, AAAA and PTR records
        loadbalance
        # Return HTTP 200 OK on :8080 when CoreDNS is running
        health
        # Return HTTP 200 OK on :8081 when CoreDNS and plugins are ready
        ready
    }    
